# Generated by Django 4.2.4 on 2023-09-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_panel', '0004_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
    ]
