# Generated by Django 4.2.4 on 2023-09-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_panel', '0007_alter_userpassword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='dsfsdfsd', max_length=200),
            preserve_default=False,
        ),
    ]
