# Generated by Django 4.2.4 on 2023-09-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_panel', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
