# Generated by Django 4.2.4 on 2023-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
