# Generated by Django 4.2.4 on 2023-09-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_panel', '0011_customer'),
        ('home', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_c', to='a_panel.product'),
        ),
    ]
