# Generated by Django 4.2.4 on 2023-09-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_wishlist_product_wishlistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='activ',
            name='email',
            field=models.EmailField(default='rahymowahmet@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
