# Generated by Django 4.2.7 on 2024-03-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_activ_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activ',
            name='email',
        ),
    ]
